[project]
name = 'first-project'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.StackedSTX]
path = 'contracts/StackedSTX.clar'
clarity_version = 1
epoch = 2.0


[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
